### ISSUE TITLE
Segmentation fault on certain invalid URLs

### ISSUE THREAD

**Issue by blay09** [get-got/discord-downloader-go#10]
Certain messages with invalid URLs result in a segmentation fault:

**Example message to reproduce:**
`RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]`

**Logs:**
```
2021/01/24 22:18:02.242994 handlers.go:69: Message [105609928126824448/374491861823520769/105608094721028096]: RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]
2021/01/24 22:18:02.248536 handlers.go:105: > FILE: https://%{HTTP_HOST}%{REQUEST_URI}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0xa55d57]
goroutine 4934 [running]:
main.tryDownload(0xc000606013, 0x22, 0x0, 0x0, 0xc00007ced0, 0x2b, 0xc0001231e0, 0x9d5b340, 0xed79fe91a, 0x10ceb20, ...)
	/discord-downloader-go/downloads.go:461 +0x4f7
main.startDownload(0xc000606013, 0x22, 0x0, 0x0, 0xc00007c9f0, 0x2a, 0xc0001231e0, 0x9d5b340, 0xed79fe91a, 0x10ceb20, ...)
	/discord-downloader-go/downloads.go:390 +0x195
main.handleMessage(0xc0001231e0, 0xc000704200)
	/discord-downloader-go/handlers.go:107 +0x5dd
main.messageCreate(0xc00010e240, 0xc00000ebb0)
	/discord-downloader-go/handlers.go:31 +0x33
github.com/bwmarrin/discordgo.messageCreateEventHandler.Handle(0xc3aae0, 0xc00010e240, 0xb30700, 0xc00000ebb0)
	/go/pkg/mod/github.com/bwmarrin/discordgo@v0.22.0/eventhandlers.go:497 +0x4b
created by github.com/bwmarrin/discordgo.(*Session).handle
	/go/pkg/mod/github.com/bwmarrin/discordgo@v0.22.0/event.go:171 +0x111
```

Running on Docker (custom alpine-based image) but most likely reproducible in all other environments too.

This happens on both newly posted messages as well as when downloading history (history download will not be able to go past that message unless it is deleted).

**Comment by get-got** [comment]
@blay09 Thanks for catching this and giving such an apt description, made it very quick to fix.

https://github.com/get-got/discord-downloader-go/commit/fe53f143150a0308a7a7a9f2a14f0a38f6409199
